apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bootcampapp-mg3f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bootcampapp-mg3f
    app.kubernetes.io/part-of: bootcampapp
  name: bootcampapp-mg3f
  namespace: utherp0-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bootcampapp-mg3f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bootcampapp-mg3f
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:d09a73ef2f03cd9f6acad0b4ea78828d492e22fcdaaf0002c2a6b8a049bf9d88
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
